version: '3'
services:
  postgres:
    image: postgres:alpine
    container_name: postgres_nestjs
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "3001:5432"
    env_file:
      - .env-docker
    restart: always
  adminer:
    image:  adminer:standalone
    restart: always
    ports:
      - 3002:8080
    depends_on:
      - postgres
    
  mongo:
    image: mongo
    container_name: mongo_nestjs
    ports:
      - "3003:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    env_file:
      - .env-docker
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 3004:8081
    depends_on:
      - mongo
    env_file:
      - .env-docker

volumes:
  pg_data:
  mongo_data:
networks:
  default:
    driver: bridge
