services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'nest-mono-rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rmq_lib:/var/lib/rabbitmq
      - rmq_log:/var/log/rabbitmq
    env_file:
      - '.env-docker'

volumes:
  rmq_lib:
  rmq_log:

networks:
  default:
    driver: bridge
